# Generated by Django 3.1 on 2020-10-05 02:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время выплаты')),
                ('payment_amount', models.PositiveIntegerField(default=0, verbose_name='Сумма')),
                ('comment', models.CharField(default='', max_length=250, verbose_name='Комментарий')),
                ('confirm', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'оплата',
                'verbose_name_plural': 'оплаты',
            },
        ),
        migrations.CreateModel(
            name='Treasurer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treasurer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Казначей')),
            ],
            options={
                'verbose_name': 'Казначей',
                'verbose_name_plural': 'Казначеи',
            },
        ),
        migrations.CreateModel(
            name='TreasurerPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Payments.payment', verbose_name='Выплата')),
                ('treasurer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Payments.treasurer', verbose_name='Казначей')),
                ('whom', models.ManyToManyField(related_name='whom', to=settings.AUTH_USER_MODEL, verbose_name='Кому')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
