# Generated by Django 3.1 on 2020-10-05 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='treasurerpayment',
            options={'verbose_name': 'Выплата казначеем', 'verbose_name_plural': 'Выплаты казначеев'},
        ),
    ]
