# Generated by Django 3.1 on 2020-10-05 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0002_auto_20201005_0512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='confirm',
            field=models.BooleanField(default=False, verbose_name='Уплачено'),
        ),
    ]
