# Generated by Django 3.1 on 2020-10-05 03:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0003_auto_20201005_0633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Время выплаты'),
        ),
    ]
