# Generated by Django 3.1 on 2020-10-05 04:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Payments', '0005_auto_20201005_0635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treasurerpayment',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='treasurerpayment',
            name='whom',
        ),
        migrations.CreateModel(
            name='UserPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Payments.payment', verbose_name='Выплата')),
                ('whom_payed', models.ManyToManyField(related_name='whom_payed', to=settings.AUTH_USER_MODEL, verbose_name='Кому')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='treasurerpayment',
            name='users_payments',
            field=models.ManyToManyField(to='Payments.UserPayment', verbose_name='Выплата'),
        ),
    ]
