# Generated by Django 3.1 on 2020-10-06 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Payments', '0007_auto_20201005_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='whom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Кому'),
        ),
        migrations.AlterField(
            model_name='treasurerpayment',
            name='users_payments',
            field=models.ManyToManyField(to='Payments.Payment', verbose_name='Выплата'),
        ),
        migrations.DeleteModel(
            name='UserPayment',
        ),
    ]
