# Generated by Django 3.1 on 2020-10-20 20:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Payments', '0010_auto_20201020_0406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='whom',
        ),
        migrations.AddField(
            model_name='payment',
            name='whom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Кому'),
        ),
    ]
