# Generated by Django 3.1 on 2020-10-21 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0011_auto_20201020_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='comment',
            field=models.CharField(default='', max_length=250, verbose_name='За что произведена'),
        ),
    ]
