# Generated by Django 3.1 on 2020-09-28 02:46

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок')),
                ('text', ckeditor.fields.RichTextField(max_length=4200, verbose_name='Текст')),
                ('footer', ckeditor.fields.RichTextField(default='', max_length=200, verbose_name='Подвал')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Видимость')),
                ('reminder', models.CharField(blank=True, default='', max_length=150, verbose_name='Небольшая пометка')),
            ],
            options={
                'verbose_name': 'статья',
                'verbose_name_plural': 'статьи',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('text', ckeditor.fields.RichTextField(max_length=4200, verbose_name='Текст')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Видимость')),
                ('reminder', models.CharField(blank=True, default='', max_length=150, verbose_name='Небольшая пометка')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': "FAQ's",
            },
        ),
    ]
