# Generated by Django 3.1 on 2020-09-28 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='New',
        ),
        migrations.AlterModelOptions(
            name='new',
            options={'verbose_name': 'новость', 'verbose_name_plural': 'новости'},
        ),
    ]
