# Generated by Django 3.1 on 2020-09-23 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(default='', max_length=50, verbose_name='Тип активности')),
            ],
            options={
                'verbose_name': 'активность',
                'verbose_name_plural': 'активности',
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='statistic.activity', verbose_name='Активность')),
                ('user_activity', models.ManyToManyField(related_name='user_activity', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'пользовательская активность',
                'verbose_name_plural': 'пользовательские активности',
            },
        ),
        migrations.DeleteModel(
            name='PVEActivity',
        ),
        migrations.DeleteModel(
            name='PVPActivity',
        ),
    ]
