# Generated by Django 3.1 on 2020-09-24 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0002_auto_20200923_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_hidden',
            field=models.BooleanField(default=False, verbose_name='Почта скрыта'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_hidden',
            field=models.BooleanField(default=False, verbose_name='Номер скрыт'),
        ),
    ]
