# Generated by Django 3.1 on 2020-09-25 10:17

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0003_auto_20200924_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='footer',
            field=ckeditor.fields.RichTextField(default='', max_length=200, verbose_name='Подвал'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='city',
            field=models.CharField(max_length=50, null=True, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
    ]
