# Generated by Django 3.1 on 2020-09-26 11:37

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0004_auto_20200925_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='footer',
            field=ckeditor.fields.RichTextField(default='', max_length=200, verbose_name='Подвал'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Адрес электронной почты'),
        ),
    ]
