# Generated by Django 3.1 on 2020-09-26 19:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0005_auto_20200926_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='join_data',
            field=models.DateField(default=datetime.datetime(2020, 9, 26, 22, 3, 9, 882512), verbose_name='Дата вступления'),
        ),
    ]
