# Generated by Django 3.1 on 2020-09-26 19:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0006_customuser_join_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='join_data',
            field=models.DateField(default=datetime.datetime(2020, 9, 26, 22, 10, 37, 409752), verbose_name='Дата вступления'),
        ),
    ]
