# Generated by Django 3.1 on 2020-09-26 19:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0008_auto_20200926_2211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='join_data',
        ),
        migrations.AddField(
            model_name='customuser',
            name='join_date',
            field=models.DateField(default=datetime.datetime(2020, 9, 26, 22, 13, 59, 188157), verbose_name='Дата вступления'),
        ),
    ]
