# Generated by Django 3.1 on 2020-09-26 20:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0009_auto_20200926_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='join_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата вступления'),
        ),
        migrations.AlterField(
            model_name='recruit',
            name='week',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата'),
        ),
    ]
