# Generated by Django 3.1 on 2020-09-26 22:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0010_auto_20200926_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 26, 22, 0, 38, 681660, tzinfo=utc), verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='join_date',
            field=models.DateField(default=datetime.datetime(2020, 9, 26, 22, 0, 38, 648607, tzinfo=utc), verbose_name='Дата вступления'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 26, 22, 0, 38, 685166, tzinfo=utc), verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 26, 22, 0, 38, 679657, tzinfo=utc), verbose_name='Время выплаты'),
        ),
        migrations.AlterField(
            model_name='primetime',
            name='beginning',
            field=models.TimeField(default=datetime.datetime(2020, 9, 26, 22, 0, 38, 678155, tzinfo=utc), verbose_name='Начало'),
        ),
        migrations.AlterField(
            model_name='primetime',
            name='ending',
            field=models.TimeField(default=datetime.datetime(2020, 9, 26, 22, 0, 38, 678155, tzinfo=utc), verbose_name='Конец'),
        ),
        migrations.AlterField(
            model_name='recruit',
            name='week',
            field=models.DateField(default=datetime.datetime(2020, 9, 26, 22, 0, 38, 682161, tzinfo=utc), verbose_name='Дата'),
        ),
    ]
