# Generated by Django 3.1 on 2020-09-26 22:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0011_auto_20200927_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='join_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата вступления'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время выплаты'),
        ),
        migrations.AlterField(
            model_name='primetime',
            name='beginning',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Начало'),
        ),
        migrations.AlterField(
            model_name='primetime',
            name='ending',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Конец'),
        ),
        migrations.AlterField(
            model_name='recruit',
            name='week',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата'),
        ),
    ]
