# Generated by Django 3.1 on 2020-09-27 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0012_auto_20200927_0101'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ментор')),
            ],
            options={
                'verbose_name': 'ментор',
                'verbose_name_plural': 'менторы',
            },
        ),
        migrations.CreateModel(
            name='Mentoring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction_of_development', models.ManyToManyField(to='statistic.Activity', verbose_name='Направления развития')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statistic.mentor', verbose_name='Ментор')),
                ('people', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Сопровождаемые')),
            ],
            options={
                'verbose_name': 'менторство',
                'verbose_name_plural': 'менторство',
            },
        ),
    ]
