# Generated by Django 3.1 on 2020-10-01 18:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0014_auto_20200928_0546'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, default='', max_length=9000, verbose_name='Сообщения')),
                ('by', models.ManyToManyField(related_name='by', to=settings.AUTH_USER_MODEL, verbose_name='От')),
                ('to', models.ManyToManyField(related_name='to', to=settings.AUTH_USER_MODEL, verbose_name='Для')),
            ],
            options={
                'verbose_name': 'сообщание',
                'verbose_name_plural': 'сообщания',
            },
        ),
    ]
