# Generated by Django 3.1 on 2020-10-01 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0015_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='by',
        ),
        migrations.AddField(
            model_name='message',
            name='by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='by', to=settings.AUTH_USER_MODEL, verbose_name='От'),
        ),
    ]
