# Generated by Django 3.1 on 2020-10-02 23:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0016_auto_20201001_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(blank=True, default='', max_length=9000, verbose_name='Сообщение'),
        ),
        migrations.CreateModel(
            name='UserPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payments', models.ManyToManyField(related_name='payments', to='statistic.PaymentAmount', verbose_name='Выплаты')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_payment', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'зарплата',
                'verbose_name_plural': 'зарплаты',
            },
        ),
    ]
