# Generated by Django 3.1 on 2020-09-23 17:28

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_text', ckeditor.fields.RichTextField(max_length=4200, verbose_name='Текст')),
                ('deathline', models.DateField(default=datetime.datetime(2020, 9, 26, 20, 28, 29, 801283), verbose_name='Дедлайн')),
                ('executed', models.NullBooleanField(default=False, verbose_name='Исполнено')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
    ]
