# Generated by Django 3.1 on 2020-09-23 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('SRM', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='task_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_from', to=settings.AUTH_USER_MODEL, verbose_name='От'),
        ),
        migrations.AddField(
            model_name='order',
            name='task_to',
            field=models.ManyToManyField(blank=True, related_name='task_to', to=settings.AUTH_USER_MODEL, verbose_name='Кому'),
        ),
        migrations.AddField(
            model_name='order',
            name='task_to_group',
            field=models.ManyToManyField(blank=True, related_name='task_to_group', to='auth.Group', verbose_name='Группе'),
        ),
    ]
