# Generated by Django 3.1 on 2020-09-23 17:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SRM', '0002_auto_20200923_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deathline',
            field=models.DateField(default=datetime.datetime(2020, 9, 26, 20, 34, 41, 299647), verbose_name='Дедлайн'),
        ),
    ]
