# Generated by Django 3.1 on 2020-09-24 09:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SRM', '0004_auto_20200923_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deathline',
            field=models.DateField(default=datetime.datetime(2020, 9, 27, 12, 51, 41, 925071), verbose_name='Дедлайн'),
        ),
    ]
