# Generated by Django 3.1 on 2020-09-24 13:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SRM', '0005_auto_20200924_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='post_date',
            field=models.DateField(default=datetime.datetime(2020, 9, 24, 16, 36, 11, 933169), verbose_name='Дата размещения'),
        ),
        migrations.AlterField(
            model_name='order',
            name='deathline',
            field=models.DateField(default=datetime.datetime(2020, 9, 27, 16, 36, 11, 933169), verbose_name='Дедлайн'),
        ),
    ]
