# Generated by Django 3.1 on 2020-09-24 13:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SRM', '0006_auto_20200924_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='topic',
            field=models.CharField(default='', max_length=150, verbose_name='Тема'),
        ),
        migrations.AlterField(
            model_name='order',
            name='deathline',
            field=models.DateField(default=datetime.datetime(2020, 9, 27, 16, 49, 46, 636106), verbose_name='Дедлайн'),
        ),
        migrations.AlterField(
            model_name='order',
            name='post_date',
            field=models.DateField(default=datetime.datetime(2020, 9, 24, 16, 49, 46, 636106), verbose_name='Дата размещения'),
        ),
    ]
