# Generated by Django 3.1 on 2020-09-24 15:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SRM', '0007_auto_20200924_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deathline',
            field=models.DateField(default=datetime.datetime(2020, 9, 27, 18, 53, 43, 519324), verbose_name='Дедлайн'),
        ),
        migrations.AlterField(
            model_name='order',
            name='post_date',
            field=models.DateField(default=datetime.datetime(2020, 9, 24, 18, 53, 43, 519324), verbose_name='Дата размещения'),
        ),
        migrations.AlterField(
            model_name='order',
            name='task_text',
            field=models.TextField(max_length=4200, verbose_name='Текст'),
        ),
    ]
