# Generated by Django 3.1 on 2020-09-25 10:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SRM', '0008_auto_20200924_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deathline',
            field=models.DateField(default=datetime.datetime(2020, 9, 28, 13, 17, 14, 787117), verbose_name='Дедлайн'),
        ),
        migrations.AlterField(
            model_name='order',
            name='post_date',
            field=models.DateField(default=datetime.datetime(2020, 9, 25, 13, 17, 14, 787117), verbose_name='Дата размещения'),
        ),
    ]
