# Generated by Django 3.1 on 2020-09-26 11:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SRM', '0009_auto_20200925_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deathline',
            field=models.DateField(default=datetime.datetime(2020, 9, 29, 14, 37, 20, 110763), verbose_name='Дедлайн'),
        ),
        migrations.AlterField(
            model_name='order',
            name='post_date',
            field=models.DateField(default=datetime.datetime(2020, 9, 26, 14, 37, 20, 110763), verbose_name='Дата размещения'),
        ),
    ]
