# Generated by Django 3.1 on 2020-09-26 17:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SRM', '0010_auto_20200926_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deathline',
            field=models.DateField(default=datetime.datetime(2020, 9, 29, 20, 49, 13, 429329), verbose_name='Дедлайн'),
        ),
        migrations.AlterField(
            model_name='order',
            name='executed',
            field=models.BooleanField(default=False, verbose_name='Исполнено'),
        ),
        migrations.AlterField(
            model_name='order',
            name='post_date',
            field=models.DateField(default=datetime.datetime(2020, 9, 26, 20, 49, 13, 429329), verbose_name='Дата размещения'),
        ),
    ]
