# Generated by Django 3.1 on 2020-09-26 19:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SRM', '0012_auto_20200926_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deathline',
            field=models.DateField(default=datetime.datetime(2020, 9, 29, 22, 10, 37, 557990), verbose_name='Дедлайн'),
        ),
        migrations.AlterField(
            model_name='order',
            name='post_date',
            field=models.DateField(default=datetime.datetime(2020, 9, 26, 22, 10, 37, 557990), verbose_name='Дата размещения'),
        ),
    ]
