# Generated by Django 3.1 on 2020-09-27 13:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('SRM', '0022_auto_20200927_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deathline',
            field=models.DateField(default=datetime.datetime(2020, 9, 30, 13, 28, 1, 936276, tzinfo=utc), verbose_name='Дедлайн'),
        ),
        migrations.AlterField(
            model_name='order',
            name='post_date',
            field=models.DateField(default=datetime.datetime(2020, 9, 27, 13, 28, 1, 936276, tzinfo=utc), verbose_name='Дата размещения'),
        ),
    ]
