# Generated by Django 3.1 on 2020-09-27 13:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SRM', '0023_auto_20200927_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deathline',
            field=models.DateField(default=datetime.datetime(2020, 9, 30, 13, 29, 23, 444599, tzinfo=utc), verbose_name='Дедлайн'),
        ),
        migrations.AlterField(
            model_name='order',
            name='post_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата размещения'),
        ),
    ]
