# Generated by Django 3.1 on 2020-09-27 19:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('SRM', '0024_auto_20200927_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deathline',
            field=models.DateField(default=datetime.datetime(2020, 9, 30, 19, 53, 44, 219576, tzinfo=utc), verbose_name='Дедлайн'),
        ),
    ]
