# Generated by Django 3.1 on 2020-09-27 22:39

import ckeditor.fields
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('SRM', '0025_auto_20200927_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='implementation_report',
            field=ckeditor.fields.RichTextField(default='', max_length=4200, verbose_name='Отчёт о выполнении'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='deathline',
            field=models.DateField(default=datetime.datetime(2020, 9, 30, 22, 39, 24, 271343, tzinfo=utc), verbose_name='Дедлайн'),
        ),
        migrations.AlterField(
            model_name='order',
            name='task_text',
            field=ckeditor.fields.RichTextField(max_length=4200, verbose_name='Текст'),
        ),
    ]
