# Generated by Django 3.1 on 2020-09-27 22:40

import ckeditor.fields
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('SRM', '0026_auto_20200928_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deathline',
            field=models.DateField(default=datetime.datetime(2020, 9, 30, 22, 40, 12, 992724, tzinfo=utc), verbose_name='Дедлайн'),
        ),
        migrations.AlterField(
            model_name='order',
            name='implementation_report',
            field=ckeditor.fields.RichTextField(default='', max_length=4200, verbose_name='Отчёт о выполнении'),
        ),
        migrations.AlterField(
            model_name='order',
            name='task_text',
            field=ckeditor.fields.RichTextField(default='', max_length=4200, verbose_name='Текст'),
        ),
    ]
