# Generated by Django 3.1 on 2020-09-28 02:32

import ckeditor.fields
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('SRM', '0027_auto_20200928_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deathline',
            field=models.DateField(default=datetime.datetime(2020, 10, 1, 2, 32, 8, 37276, tzinfo=utc), verbose_name='Дедлайн'),
        ),
        migrations.AlterField(
            model_name='order',
            name='implementation_report',
            field=ckeditor.fields.RichTextField(blank=True, default='', max_length=4200, verbose_name='Отчёт о выполнении'),
        ),
    ]
