# Generated by Django 3.1 on 2020-10-01 16:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('SRM', '0030_auto_20200928_0549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deathline',
            field=models.DateField(default=datetime.datetime(2020, 10, 4, 16, 45, 18, 955150, tzinfo=utc), verbose_name='Дедлайн'),
        ),
    ]
