# Generated by Django 3.1 on 2020-10-01 18:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('SRM', '0031_auto_20201001_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deathline',
            field=models.DateField(default=datetime.datetime(2020, 10, 4, 18, 2, 16, 458979, tzinfo=utc), verbose_name='Дедлайн'),
        ),
    ]
