# Generated by Django 3.1 on 2020-10-03 00:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('SRM', '0034_auto_20201003_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deathline',
            field=models.DateField(default=datetime.datetime(2020, 10, 6, 0, 22, 17, 908357, tzinfo=utc), verbose_name='Дедлайн'),
        ),
    ]
