# Generated by Django 3.1 on 2020-10-05 02:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('SRM', '0037_auto_20201004_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deathline',
            field=models.DateField(default=datetime.datetime(2020, 10, 8, 2, 10, 19, 563183, tzinfo=utc), verbose_name='Дедлайн'),
        ),
    ]
