# Generated by Django 3.1 on 2020-10-05 03:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('SRM', '0040_auto_20201005_0633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deathline',
            field=models.DateField(default=datetime.datetime(2020, 10, 8, 3, 34, 42, 449446, tzinfo=utc), verbose_name='Дедлайн'),
        ),
    ]
