# Generated by Django 3.1 on 2020-10-05 04:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('SRM', '0045_auto_20201005_0704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deathline',
            field=models.DateField(default=datetime.datetime(2020, 10, 8, 4, 6, 12, 525822, tzinfo=utc), verbose_name='Дедлайн'),
        ),
    ]
