# Generated by Django 3.1 on 2020-10-05 04:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('SRM', '0046_auto_20201005_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deathline',
            field=models.DateField(default=datetime.datetime(2020, 10, 8, 4, 43, 10, 738587, tzinfo=utc), verbose_name='Дедлайн'),
        ),
    ]
