# Generated by Django 3.1 on 2020-10-05 15:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('SRM', '0047_auto_20201005_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deathline',
            field=models.DateField(default=datetime.datetime(2020, 10, 8, 15, 24, 47, 287615, tzinfo=utc), verbose_name='Дедлайн'),
        ),
    ]
