# Generated by Django 3.1 on 2020-10-06 11:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('SRM', '0052_auto_20201006_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deathline',
            field=models.DateField(default=datetime.datetime(2020, 10, 9, 11, 21, 57, 90335, tzinfo=utc), verbose_name='Дедлайн'),
        ),
    ]
