# Generated by Django 3.1 on 2020-10-07 01:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('SRM', '0054_auto_20201007_0404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deathline',
            field=models.DateField(default=datetime.datetime(2020, 10, 10, 1, 15, 59, 828919, tzinfo=utc), verbose_name='Дедлайн'),
        ),
    ]
