# Generated by Django 3.1 on 2020-10-07 01:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('SRM', '0056_auto_20201007_0436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deathline',
            field=models.DateField(default=datetime.datetime(2020, 10, 10, 1, 45, 58, 638322, tzinfo=utc), verbose_name='Дедлайн'),
        ),
    ]
