# Generated by Django 3.1 on 2020-10-20 01:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('SRM', '0057_auto_20201007_0446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deathline',
            field=models.DateField(default=datetime.datetime(2020, 10, 23, 1, 6, 21, 738327, tzinfo=utc), verbose_name='Дедлайн'),
        ),
    ]
