# Generated by Django 3.1 on 2020-10-20 20:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('SRM', '0058_auto_20201020_0406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deathline',
            field=models.DateField(default=datetime.datetime(2020, 10, 23, 20, 46, 2, 943378, tzinfo=utc), verbose_name='Дедлайн'),
        ),
    ]
