# Generated by Django 3.1 on 2020-10-21 00:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('SRM', '0059_auto_20201020_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deathline',
            field=models.DateField(default=datetime.datetime(2020, 10, 24, 0, 3, 16, 940867, tzinfo=utc), verbose_name='Дедлайн'),
        ),
    ]
